### ISSUE TITLE
`blurb test` lacks test data

### ISSUE THREAD

**Issue by pitrou** [python/blurb#1]
```pytb
$ ~/cpython/default/python -m blurb.blurb test
-------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/antoine/cpython/default/Lib/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/antoine/cpython/default/Lib/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/antoine/cpython/core-workflow/blurb/blurb.py", line 1514, in <module>
    main()
  File "/home/antoine/cpython/core-workflow/blurb/blurb.py", line 1429, in main
    sys.exit(fn(*args))
  File "/home/antoine/cpython/core-workflow/blurb/blurb.py", line 742, in test
    fn()
  File "/home/antoine/cpython/core-workflow/blurb/blurb.py", line 595, in test_files
    with pushd(self.directory):
  File "/home/antoine/cpython/core-workflow/blurb/blurb.py", line 181, in __enter__
    os.chdir(self.path)
FileNotFoundError: [Errno 2] No such file or directory: 'tests/fail'
```

**Comment by hugovk** [comment]
Tests can be run by installing with pip and then `blurb test`, or for a specific version:

```console
❯ ../python/cpython/main/python.exe src/blurb test
-------------------------------------------------------------------------------
.................
17 tests passed.
```

And tox can also be used (e.g. `tox -e py313`) to run these tests and the unit tests with pytest.

Is this issue still needed? Please re-open if so.
